/* 
 * @(#)ConnectionTypeEnum.java        1.0 19/01/15
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "device-management", revision: "2014-07-26".
 */

package net.juniper.yang.mo.deviceManagement;

import com.tailf.jnc.YangEnumeration;
import com.tailf.jnc.YangException;

/**
 * This class represents an element from 
 * the namespace 
 * generated to "/home/maxin/space/js-ems/server/target/scala-2.11/src_managed/main/net/juniper/yang/mo/deviceManagement/connectionTypeEnum"
 * <p>
 * See line 114 in
 * /home/maxin/space/js-ems/server/src/main/resources/yang/device-management.yang
 *
 * @version 1.0 2015-01-19
 * @author Auto Generated
 */
public class ConnectionTypeEnum extends YangEnumeration {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for ConnectionTypeEnum object from a string.
     * @param value Value to construct the ConnectionTypeEnum from.
     */
    public ConnectionTypeEnum(String value) throws YangException {
        super(value,
            new String[] {
                "UNKNOWN",
                "REACHABLE",
                "UNREACHABLE",
                "MODELED",
                "MASTERBULK",
                "APPINIT",
                "APPINITADAPTED",
            }
        );
        check();
    }

    /**
     * Sets the value using a string value.
     * @param value The value to set.
     */
    public void setValue(String value) throws YangException {
        super.setValue(value);
        check();
    }

    /**
     * Checks all restrictions (if any).
     */
    public void check() throws YangException {
        super.check();
    }

}
