/* 
 * @(#)Devicemgt.java        1.0 19/01/15
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "device-management", revision: "2014-07-26".
 */

package net.juniper.yang.mo.deviceManagement;

import com.tailf.jnc.JNCException;
import com.tailf.jnc.SchemaNode;
import com.tailf.jnc.SchemaParser;
import com.tailf.jnc.SchemaTree;
import com.tailf.jnc.Tagpath;
import com.tailf.jnc.YangElement;

import java.util.HashMap;

/**
 * The root class for namespace http://juniper.net/ns/space/device-management/1.0 (accessible from 
 * DeviceManagement.NAMESPACE) with prefix "devicemgt" (DeviceManagement.PREFIX).
 *
 * @version 1.0 2015-01-19
 * @author Auto Generated
 */
public class Devicemgt {

    public static final String NAMESPACE = "http://juniper.net/ns/space/device-management/1.0";

    public static final String PREFIX = "devicemgt";

    private static boolean enabled = false;

    /**
     * Enable the elements in this namespace to be aware
     * of the data model and use the generated classes.
     */
    public static void enable() {

        if(enabled)
            return;
        try {
            YangElement.setPackage(NAMESPACE, "net.juniper.yang.mo.deviceManagement");
            Devicemgt.registerSchema();
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        try{
            String clazz=System.getProperty("yang.type.observer");
            Class.forName(clazz).getMethod("registerYangTypeHander", String.class).invoke( Class.forName(clazz).newInstance(),NAMESPACE);
        }
        catch(Exception e){
            e.printStackTrace();
        }


    }

    /**
     * Register the schema for this namespace in the global
     * schema table (CsTree) making it possible to lookup
     * CsNode entries for all tagpaths
     */
    public static void registerSchema() throws JNCException {
        SchemaParser parser = new SchemaParser();
        HashMap<Tagpath, SchemaNode> h = SchemaTree.create(NAMESPACE);
        parser.findAndReadFile("Devicemgt.schema", h, Devicemgt.class);
    }

}
