/* 
 * @(#)Modules.java        1.0 26/12/14
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "paradigmmgt", revision: "2014-09-16".
 */

package net.juniper.jspace.ems.yang.paradigmmgt.paradigmmgt;

import com.tailf.jnc.Element;
import com.tailf.jnc.ElementChildrenIterator;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.Tagpath;
import com.tailf.jnc.YangElement;
import com.tailf.jnc.YangUInt32;

import net.juniper.jspace.ems.yang.paradigmmgt.Paramgt;
import net.juniper.jspace.ems.yang.paradigmmgt.paradigmmgt.modules.Module;

/**
 * This class represents an element from 
 * the namespace http://juniper.net/ns/space/paradigm/1.0
 * generated to "src/net/juniper/jspace/ems/yang/paradigmmgt/paradigmmgt/modules"
 * <p>
 * See line 17 in
 * /home/maxin/workspace/js-easy-rest/easy-rest-core/yang/paradigmmgt.yang
 *
 * @version 1.0 2014-12-26
 * @author Auto Generated
 */
public class Modules extends YangElement {

    private static final long serialVersionUID = 1L;

    public static final Tagpath tagpath = new Tagpath("paradigmmgt/paradigmmgt/modules");

    static {
        Paramgt.enable();
    }

    /**
     * Constructor for an empty Modules object.
     */
    public Modules() {
        super(Paramgt.NAMESPACE, "modules");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Modules clone() {
        return (Modules)cloneContent(new Modules());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Modules cloneShallow() {
        return (Modules)cloneShallowContent(new Modules());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "module",
        };
    }

    /* Access methods for list child: "module". */

    /**
     * Gets list entry "module", with specified keys.
     * @param idValue Key argument of child.
     */
    public Module getModule(YangUInt32 idValue) throws JNCException {
        String path = "module[id='" + idValue + "']";
        return (Module)searchOne(path);
    }

    /**
     * Gets list entry "module", with specified keys.
     * The keys are specified as strings.
     * @param idValue Key argument of child.
     */
    public Module getModule(String idValue) throws JNCException {
        String path = "module[id='" + idValue + "']";
        return (Module)searchOne(path);
    }

    /**
     * Iterator method for the list "module".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator moduleIterator() {
        return new ElementChildrenIterator(children, "module");
    }

    /**
     * Adds list entry "module", using an existing object.
     * @param module The object to add.
     * @return The added child.
     */
    public Module addModule(Module module) throws JNCException {
        insertChild(module, childrenNames());
        return module;
    }

    /**
     * Adds list entry "module", with specified keys.
     * @param idValue Key argument of child.
     * @return The added child.
     */
    public Module addModule(YangUInt32 idValue) throws JNCException {
        Module module = new Module(idValue);
        return addModule(module);
    }

    /**
     * Adds list entry "module", with specified keys.
     * The keys are specified as strings.
     * @param idValue Key argument of child.
     * @return The added child.
     */
    public Module addModule(String idValue) throws JNCException {
        Module module = new Module(idValue);
        return addModule(module);
    }

    /**
     * Adds list entry "module".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Module addModule() throws JNCException {
        Module module = new Module();
        insertChild(module, childrenNames());
        return module;
    }

    /**
     * Deletes list entry "module", with specified keys.
     * @param idValue Key argument of child.
     */
    public void deleteModule(YangUInt32 idValue) throws JNCException {
        String path = "module[id='" + idValue + "']";
        delete(path);
    }

    /**
     * Deletes list entry "module", with specified keys.
     * The keys are specified as strings.
     * @param idValue Key argument of child.
     */
    public void deleteModule(String idValue) throws JNCException {
        String path = "module[id='" + idValue + "']";
        delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
