/* 
 * @(#)Workspaces.java        1.0 26/12/14
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "paradigmmgt", revision: "2014-09-16".
 */

package net.juniper.jspace.ems.yang.paradigmmgt.paradigmmgt.modules.module;

import com.tailf.jnc.Element;
import com.tailf.jnc.ElementChildrenIterator;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.Tagpath;
import com.tailf.jnc.YangElement;
import com.tailf.jnc.YangUInt32;

import net.juniper.jspace.ems.yang.paradigmmgt.Paramgt;
import net.juniper.jspace.ems.yang.paradigmmgt.paradigmmgt.modules.module.workspaces.Workspace;

/**
 * This class represents an element from 
 * the namespace http://juniper.net/ns/space/paradigm/1.0
 * generated to "src/net/juniper/jspace/ems/yang/paradigmmgt/paradigmmgt/modules/module/workspaces"
 * <p>
 * See line 27 in
 * /home/maxin/workspace/js-easy-rest/easy-rest-core/yang/paradigmmgt.yang
 *
 * @version 1.0 2014-12-26
 * @author Auto Generated
 */
public class Workspaces extends YangElement {

    private static final long serialVersionUID = 1L;

    public static final Tagpath tagpath = new Tagpath("paradigmmgt/paradigmmgt/modules/module/workspaces");

    static {
        Paramgt.enable();
    }

    /**
     * Constructor for an empty Workspaces object.
     */
    public Workspaces() {
        super(Paramgt.NAMESPACE, "workspaces");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Workspaces clone() {
        return (Workspaces)cloneContent(new Workspaces());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Workspaces cloneShallow() {
        return (Workspaces)cloneShallowContent(new Workspaces());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "workspace",
        };
    }

    /* Access methods for list child: "workspace". */

    /**
     * Gets list entry "workspace", with specified keys.
     * @param idValue Key argument of child.
     */
    public Workspace getWorkspace(YangUInt32 idValue) throws JNCException {
        String path = "workspace[id='" + idValue + "']";
        return (Workspace)searchOne(path);
    }

    /**
     * Gets list entry "workspace", with specified keys.
     * The keys are specified as strings.
     * @param idValue Key argument of child.
     */
    public Workspace getWorkspace(String idValue) throws JNCException {
        String path = "workspace[id='" + idValue + "']";
        return (Workspace)searchOne(path);
    }

    /**
     * Iterator method for the list "workspace".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator workspaceIterator() {
        return new ElementChildrenIterator(children, "workspace");
    }

    /**
     * Adds list entry "workspace", using an existing object.
     * @param workspace The object to add.
     * @return The added child.
     */
    public Workspace addWorkspace(Workspace workspace) throws JNCException {
        insertChild(workspace, childrenNames());
        return workspace;
    }

    /**
     * Adds list entry "workspace", with specified keys.
     * @param idValue Key argument of child.
     * @return The added child.
     */
    public Workspace addWorkspace(YangUInt32 idValue) throws JNCException {
        Workspace workspace = new Workspace(idValue);
        return addWorkspace(workspace);
    }

    /**
     * Adds list entry "workspace", with specified keys.
     * The keys are specified as strings.
     * @param idValue Key argument of child.
     * @return The added child.
     */
    public Workspace addWorkspace(String idValue) throws JNCException {
        Workspace workspace = new Workspace(idValue);
        return addWorkspace(workspace);
    }

    /**
     * Adds list entry "workspace".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Workspace addWorkspace() throws JNCException {
        Workspace workspace = new Workspace();
        insertChild(workspace, childrenNames());
        return workspace;
    }

    /**
     * Deletes list entry "workspace", with specified keys.
     * @param idValue Key argument of child.
     */
    public void deleteWorkspace(YangUInt32 idValue) throws JNCException {
        String path = "workspace[id='" + idValue + "']";
        delete(path);
    }

    /**
     * Deletes list entry "workspace", with specified keys.
     * The keys are specified as strings.
     * @param idValue Key argument of child.
     */
    public void deleteWorkspace(String idValue) throws JNCException {
        String path = "workspace[id='" + idValue + "']";
        delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
