/* 
 * @(#)Preferences.java        1.0 26/12/14
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "usermgt", revision: "2014-09-16".
 */

package net.juniper.jspace.ems.yang.usermgt.users.user;

import com.tailf.jnc.Element;
import com.tailf.jnc.ElementChildrenIterator;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.Tagpath;
import com.tailf.jnc.YangElement;
import com.tailf.jnc.YangUInt32;

import net.juniper.jspace.ems.yang.usermgt.Usermgt;
import net.juniper.jspace.ems.yang.usermgt.users.user.preferences.Preference;

/**
 * This class represents an element from 
 * the namespace http://juniper.net/ns/space/usermgt/1.0
 * generated to "src/net/juniper/jspace/ems/yang/usermgt/users/user/preferences"
 * <p>
 * See line 23 in
 * /home/maxin/workspace/js-easy-rest/easy-rest-core/yang/usermgt.yang
 *
 * @version 1.0 2014-12-26
 * @author Auto Generated
 */
public class Preferences extends YangElement {

    private static final long serialVersionUID = 1L;

    public static final Tagpath tagpath = new Tagpath("usermgt/users/user/preferences");

    static {
        Usermgt.enable();
    }

    /**
     * Constructor for an empty Preferences object.
     */
    public Preferences() {
        super(Usermgt.NAMESPACE, "preferences");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Preferences clone() {
        return (Preferences)cloneContent(new Preferences());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Preferences cloneShallow() {
        return (Preferences)cloneShallowContent(new Preferences());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "preference",
        };
    }

    /* Access methods for list child: "preference". */

    /**
     * Gets list entry "preference", with specified keys.
     * @param idValue Key argument of child.
     */
    public Preference getPreference(YangUInt32 idValue) throws JNCException {
        String path = "preference[id='" + idValue + "']";
        return (Preference)searchOne(path);
    }

    /**
     * Gets list entry "preference", with specified keys.
     * The keys are specified as strings.
     * @param idValue Key argument of child.
     */
    public Preference getPreference(String idValue) throws JNCException {
        String path = "preference[id='" + idValue + "']";
        return (Preference)searchOne(path);
    }

    /**
     * Iterator method for the list "preference".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator preferenceIterator() {
        return new ElementChildrenIterator(children, "preference");
    }

    /**
     * Adds list entry "preference", using an existing object.
     * @param preference The object to add.
     * @return The added child.
     */
    public Preference addPreference(Preference preference) throws JNCException {
        insertChild(preference, childrenNames());
        return preference;
    }

    /**
     * Adds list entry "preference", with specified keys.
     * @param idValue Key argument of child.
     * @return The added child.
     */
    public Preference addPreference(YangUInt32 idValue) throws JNCException {
        Preference preference = new Preference(idValue);
        return addPreference(preference);
    }

    /**
     * Adds list entry "preference", with specified keys.
     * The keys are specified as strings.
     * @param idValue Key argument of child.
     * @return The added child.
     */
    public Preference addPreference(String idValue) throws JNCException {
        Preference preference = new Preference(idValue);
        return addPreference(preference);
    }

    /**
     * Adds list entry "preference".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Preference addPreference() throws JNCException {
        Preference preference = new Preference();
        insertChild(preference, childrenNames());
        return preference;
    }

    /**
     * Deletes list entry "preference", with specified keys.
     * @param idValue Key argument of child.
     */
    public void deletePreference(YangUInt32 idValue) throws JNCException {
        String path = "preference[id='" + idValue + "']";
        delete(path);
    }

    /**
     * Deletes list entry "preference", with specified keys.
     * The keys are specified as strings.
     * @param idValue Key argument of child.
     */
    public void deletePreference(String idValue) throws JNCException {
        String path = "preference[id='" + idValue + "']";
        delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
