/* 
 * @(#)User.java        1.0 26/12/14
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "usermgt", revision: "2014-09-16".
 */

package net.juniper.jspace.ems.yang.usermgt.users;

import com.tailf.jnc.Element;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.Leaf;
import com.tailf.jnc.NodeSet;
import com.tailf.jnc.Tagpath;
import com.tailf.jnc.YangElement;
import com.tailf.jnc.YangString;
import com.tailf.jnc.YangUInt32;

import net.juniper.jspace.ems.yang.usermgt.Usermgt;
import net.juniper.jspace.ems.yang.usermgt.users.user.Domains;
import net.juniper.jspace.ems.yang.usermgt.users.user.Preferences;

/**
 * This class represents an element from 
 * the namespace http://juniper.net/ns/space/usermgt/1.0
 * generated to "src/net/juniper/jspace/ems/yang/usermgt/users/user"
 * <p>
 * See line 18 in
 * /home/maxin/workspace/js-easy-rest/easy-rest-core/yang/usermgt.yang
 *
 * @version 1.0 2014-12-26
 * @author Auto Generated
 */
public class User extends YangElement {

    private static final long serialVersionUID = 1L;

    public static final Tagpath tagpath = new Tagpath("usermgt/users/user");

    static {
        Usermgt.enable();
    }

    /**
     * Field for child container "preferences".
     */
    public Preferences preferences = null;

    /**
     * Field for child container "domains".
     */
    public Domains domains = null;

    /**
     * Constructor for an empty User object.
     */
    public User() {
        super(Usermgt.NAMESPACE, "user");
    }

    /**
     * Constructor for an initialized User object,
     * 
     * @param idValue Key argument of child.
     */
    public User(YangUInt32 idValue) throws JNCException {
        super(Usermgt.NAMESPACE, "user");
        Leaf id = new Leaf(Usermgt.NAMESPACE, "id");
        id.setValue(idValue);
        insertChild(id, childrenNames());
    }

    /**
     * Constructor for an initialized User object,
     * with String keys.
     * @param idValue Key argument of child.
     */
    public User(String idValue) throws JNCException {
        super(Usermgt.NAMESPACE, "user");
        Leaf id = new Leaf(Usermgt.NAMESPACE, "id");
        id.setValue(new YangUInt32(idValue));
        insertChild(id, childrenNames());
    }

    /**
     * Constructor for an initialized User object,
     * with keys of built in Java types.
     * @param idValue Key argument of child.
     */
    public User(long idValue) throws JNCException {
        super(Usermgt.NAMESPACE, "user");
        Leaf id = new Leaf(Usermgt.NAMESPACE, "id");
        id.setValue(new YangUInt32(idValue));
        insertChild(id, childrenNames());
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public User clone() {
        User copy;
        try {
            copy = new User(getIdValue().toString());
        } catch (JNCException e) {
            copy = null;
        }
        return (User)cloneContent(copy);
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public User cloneShallow() {
        User copy;
        try {
            copy = new User(getIdValue().toString());
        } catch (JNCException e) {
            copy = null;
        }
        return (User)cloneShallowContent(copy);
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return new String[] {
            "id",
        };
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "id",
            "name",
            "preferences",
            "domains",
        };
    }

    /* Access methods for leaf child: "id". */

    /**
     * Gets the value for child leaf "id".
     * @return The value of the leaf.
     */
    public YangUInt32 getIdValue() throws JNCException {
        return (YangUInt32)getValue("id");
    }

    /**
     * Sets the value for child leaf "id",
     * using instance of generated typedef class.
     * @param idValue The value to set.
     * @param idValue used during instantiation.
     */
    public void setIdValue(YangUInt32 idValue) throws JNCException {
        setLeafValue(Usermgt.NAMESPACE,
            "id",
            idValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "id",
     * using Java primitive values.
     * @param idValue used during instantiation.
     */
    public void setIdValue(long idValue) throws JNCException {
        setIdValue(new YangUInt32(idValue));
    }

    /**
     * Sets the value for child leaf "id",
     * using a String value.
     * @param idValue used during instantiation.
     */
    public void setIdValue(String idValue) throws JNCException {
        setIdValue(new YangUInt32(idValue));
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "id" leaf will not have a value.
     */
    public void addId() throws JNCException {
        setLeafValue(Usermgt.NAMESPACE,
            "id",
            null,
            childrenNames());
    }

    /* Access methods for optional leaf child: "name". */

    /**
     * Gets the value for child leaf "name".
     * @return The value of the leaf.
     */
    public YangString getNameValue() throws JNCException {
        return (YangString)getValue("name");
    }

    /**
     * Sets the value for child leaf "name",
     * using instance of generated typedef class.
     * @param nameValue The value to set.
     * @param nameValue used during instantiation.
     */
    public void setNameValue(YangString nameValue) throws JNCException {
        setLeafValue(Usermgt.NAMESPACE,
            "name",
            nameValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "name",
     * using a String value.
     * @param nameValue used during instantiation.
     */
    public void setNameValue(String nameValue) throws JNCException {
        setNameValue(new YangString(nameValue));
    }

    /**
     * Unsets the value for child leaf "name".
     */
    public void unsetNameValue() throws JNCException {
        delete("name");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "name" leaf will not have a value.
     */
    public void addName() throws JNCException {
        setLeafValue(Usermgt.NAMESPACE,
            "name",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "name" with operation "replace".
     */
    public void markNameReplace() throws JNCException {
        markLeafReplace("name");
    }

    /**
     * Marks the leaf "name" with operation "merge".
     */
    public void markNameMerge() throws JNCException {
        markLeafMerge("name");
    }

    /**
     * Marks the leaf "name" with operation "create".
     */
    public void markNameCreate() throws JNCException {
        markLeafCreate("name");
    }

    /**
     * Marks the leaf "name" with operation "delete".
     */
    public void markNameDelete() throws JNCException {
        markLeafDelete("name");
    }

    /* Access methods for container child: "preferences". */

    /**
     * Adds container entry "preferences", using an existing object.
     * @param preferences The object to add.
     * @return The added child.
     */
    public Preferences addPreferences(Preferences preferences)
            throws JNCException {
        this.preferences = preferences;
        insertChild(preferences, childrenNames());
        return preferences;
    }

    /**
     * Adds container entry "preferences".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Preferences addPreferences() throws JNCException {
        Preferences preferences = new Preferences();
        this.preferences = preferences;
        insertChild(preferences, childrenNames());
        return preferences;
    }

    /**
     * Deletes container entry "preferences".
     * @return An array of the deleted element nodes.
     */
    public NodeSet deletePreferences() throws JNCException {
        this.preferences = null;
        String path = "preferences";
        return delete(path);
    }

    /* Access methods for container child: "domains". */

    /**
     * Adds container entry "domains", using an existing object.
     * @param domains The object to add.
     * @return The added child.
     */
    public Domains addDomains(Domains domains) throws JNCException {
        this.domains = domains;
        insertChild(domains, childrenNames());
        return domains;
    }

    /**
     * Adds container entry "domains".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Domains addDomains() throws JNCException {
        Domains domains = new Domains();
        this.domains = domains;
        insertChild(domains, childrenNames());
        return domains;
    }

    /**
     * Deletes container entry "domains".
     * @return An array of the deleted element nodes.
     */
    public NodeSet deleteDomains() throws JNCException {
        this.domains = null;
        String path = "domains";
        return delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
        if (child instanceof Preferences) preferences = (Preferences)child;
        else if (child instanceof Domains) domains = (Domains)child;
    }

}
