/* 
 * @(#)LogicalInterfaces.java        1.0 30/12/14
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "devmgt", revision: "2014-09-16".
 */

package net.juniper.jspace.ems.yang.devmgt.devicemgt.devices.device.interfaces.interface_;

import com.tailf.jnc.Element;
import com.tailf.jnc.ElementChildrenIterator;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.Tagpath;
import com.tailf.jnc.YangElement;
import com.tailf.jnc.YangString;
import com.tailf.jnc.YangUInt32;

import net.juniper.jspace.ems.yang.devmgt.Devmgt;
import net.juniper.jspace.ems.yang.devmgt.devicemgt.devices.device.interfaces.interface_.logicalInterfaces.LogicalInterface;

/**
 * This class represents an element from 
 * the namespace http://juniper.net/ns/space/test/1.0
 * generated to "src/net/juniper/jspace/ems/yang/devmgt/devicemgt/devices/device/interfaces/interface_/logicalInterfaces"
 * <p>
 * See line 97 in
 * /home/maxin/workspace/js-easy-rest/easy-rest-core/yang/devmgt.yang
 *
 * @version 1.0 2014-12-30
 * @author Auto Generated
 */
public class LogicalInterfaces extends YangElement {

    private static final long serialVersionUID = 1L;

    public static final Tagpath tagpath = new Tagpath("devmgt/devicemgt/devices/device/interfaces/interface_/logicalInterfaces");

    static {
        Devmgt.enable();
    }

    /**
     * Constructor for an empty LogicalInterfaces object.
     */
    public LogicalInterfaces() {
        super(Devmgt.NAMESPACE, "logicalInterfaces");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public LogicalInterfaces clone() {
        return (LogicalInterfaces)cloneContent(new LogicalInterfaces());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public LogicalInterfaces cloneShallow() {
        return (LogicalInterfaces)cloneShallowContent(new LogicalInterfaces());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "size",
            "logicalInterface",
        };
    }

    /* Access methods for optional leaf child: "size". */

    /**
     * Gets the value for child leaf "size".
     * @return The value of the leaf.
     */
    public YangUInt32 getSizeValue() throws JNCException {
        return (YangUInt32)getValue("size");
    }

    /**
     * Sets the value for child leaf "size",
     * using instance of generated typedef class.
     * @param sizeValue The value to set.
     * @param sizeValue used during instantiation.
     */
    public void setSizeValue(YangUInt32 sizeValue) throws JNCException {
        setLeafValue(Devmgt.NAMESPACE,
            "size",
            sizeValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "size",
     * using Java primitive values.
     * @param sizeValue used during instantiation.
     */
    public void setSizeValue(long sizeValue) throws JNCException {
        setSizeValue(new YangUInt32(sizeValue));
    }

    /**
     * Sets the value for child leaf "size",
     * using a String value.
     * @param sizeValue used during instantiation.
     */
    public void setSizeValue(String sizeValue) throws JNCException {
        setSizeValue(new YangUInt32(sizeValue));
    }

    /**
     * Unsets the value for child leaf "size".
     */
    public void unsetSizeValue() throws JNCException {
        delete("size");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "size" leaf will not have a value.
     */
    public void addSize() throws JNCException {
        setLeafValue(Devmgt.NAMESPACE,
            "size",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "size" with operation "replace".
     */
    public void markSizeReplace() throws JNCException {
        markLeafReplace("size");
    }

    /**
     * Marks the leaf "size" with operation "merge".
     */
    public void markSizeMerge() throws JNCException {
        markLeafMerge("size");
    }

    /**
     * Marks the leaf "size" with operation "create".
     */
    public void markSizeCreate() throws JNCException {
        markLeafCreate("size");
    }

    /**
     * Marks the leaf "size" with operation "delete".
     */
    public void markSizeDelete() throws JNCException {
        markLeafDelete("size");
    }

    /* Access methods for list child: "logicalInterface". */

    /**
     * Gets list entry "logicalInterface", with specified keys.
     * @param nameValue Key argument of child.
     */
    public LogicalInterface getLogicalInterface(YangString nameValue)
            throws JNCException {
        String path = "logicalInterface[name='" + nameValue + "']";
        return (LogicalInterface)searchOne(path);
    }

    /**
     * Gets list entry "logicalInterface", with specified keys.
     * The keys are specified as strings.
     * @param nameValue Key argument of child.
     */
    public LogicalInterface getLogicalInterface(String nameValue)
            throws JNCException {
        String path = "logicalInterface[name='" + nameValue + "']";
        return (LogicalInterface)searchOne(path);
    }

    /**
     * Iterator method for the list "logicalInterface".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator logicalInterfaceIterator() {
        return new ElementChildrenIterator(children, "logicalInterface");
    }

    /**
     * Adds list entry "logicalInterface", using an existing object.
     * @param logicalInterface The object to add.
     * @return The added child.
     */
    public LogicalInterface addLogicalInterface(LogicalInterface logicalInterface)
            throws JNCException {
        insertChild(logicalInterface, childrenNames());
        return logicalInterface;
    }

    /**
     * Adds list entry "logicalInterface", with specified keys.
     * @param nameValue Key argument of child.
     * @return The added child.
     */
    public LogicalInterface addLogicalInterface(YangString nameValue)
            throws JNCException {
        LogicalInterface logicalInterface = new LogicalInterface(nameValue);
        return addLogicalInterface(logicalInterface);
    }

    /**
     * Adds list entry "logicalInterface", with specified keys.
     * The keys are specified as strings.
     * @param nameValue Key argument of child.
     * @return The added child.
     */
    public LogicalInterface addLogicalInterface(String nameValue)
            throws JNCException {
        LogicalInterface logicalInterface = new LogicalInterface(nameValue);
        return addLogicalInterface(logicalInterface);
    }

    /**
     * Adds list entry "logicalInterface".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public LogicalInterface addLogicalInterface() throws JNCException {
        LogicalInterface logicalInterface = new LogicalInterface();
        insertChild(logicalInterface, childrenNames());
        return logicalInterface;
    }

    /**
     * Deletes list entry "logicalInterface", with specified keys.
     * @param nameValue Key argument of child.
     */
    public void deleteLogicalInterface(YangString nameValue)
            throws JNCException {
        String path = "logicalInterface[name='" + nameValue + "']";
        delete(path);
    }

    /**
     * Deletes list entry "logicalInterface", with specified keys.
     * The keys are specified as strings.
     * @param nameValue Key argument of child.
     */
    public void deleteLogicalInterface(String nameValue) throws JNCException {
        String path = "logicalInterface[name='" + nameValue + "']";
        delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
